[project]
name = "lightweight-co-speech-gesture-generation"
version = "0.1.0"
description = ""
requires-python = ">=3.10,<3.12"

dependencies = [
  "tqdm",
  "tgt",
  "omegaconf",
  "numpy",
  "pandas",
  "scipy",
  "librosa",
  "wget",
  "pyrender",
  "trimesh",
  "torch",
  "smplx",
  "bitsandbytes",
  "transformers==5.*",
  "rotary-embedding-torch",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.ruff]
indent-width = 2
line-length = 80
